"""Generate drawing preview parameters from the header rule engine.

Replaces the hardcoded ``DEFAULT_PREVIEW_VALUES`` demo constants with values
generated from the actual coil inputs by the header-prepopulation engine.

Drawing parameter set (DIRECT_COIL_FIELD_REGISTRY "Drawing Parameters"):
    CD, I, S, O, R, BF, HD, HF, TF, RF, CH, SL, ZD

Mapping status (DX):
    GENERATED (HIGH engine value):  CD, TF, BF, HF, RF, HD, SL, I, O, (R when circuits+conn known)
    CONSTANT (owner rule):          ZD = 4.5 (and ZD{n})
    NOT CONNECTED (missing logic):  S, CH  -- see UNCONNECTED_PARAMS
Header assemblies 2..N (I2/S2/O2/R2/HD2/ZD2 ...) are translated from the engine's
parity-encoded per-header slots; see multi_header_logical_values.
Only HIGH engine values are emitted as generated; MEDIUM/blocked stay review.
"""

from __future__ import annotations

import re
from typing import Any

from coilforge.direct_coil.draft import DirectCoilInputDraft
from coilforge.drawing.parameters import (
    DRAWING_PARAMETER_KEYS,
    REQUIRED_PREVIEW_PARAMETER_KEYS,
    DrawingParameter,
    DrawingParameterSet,
    PreviewDefaultValue,
)
from coilforge.services.direct_coil_drawing_pipeline import build_header_request
from coilforge.services.header_prepopulate_engine import prepopulate

# Drawing param key -> scalar engine field (HIGH values).
PARAM_TO_ENGINE_FIELD: dict[str, str] = {
    "CD": "casing_depth",
    "TF": "top_flange",
    "BF": "bottom_flange",
    "HF": "header_flange",
    "RF": "return_flange",
    "HD": "suction_hd",   # return/suction header HD (3.5)
    "HDx1": "dist_hd",    # distributor header HD (4.5)
    "SL": "suction_sl",
    "I": "dist_i",        # DX distributor I
    "O": "suction_io",    # DX return I/O
}

# Drawing param key -> EZ JSON slot id (from ez_json_drawing_loader). When an EZ
# export is present these exact as-built values override the engine predictions
# for per-header positions (handles multi-circuit S, etc.).
PARAM_TO_EZ_SLOT: dict[str, str] = {
    "S": "slot.S1",      # Geometry.Headers[supply].SR (exact)
    "R": "slot.R2",      # Geometry.Headers[return].SR
    "I": "slot.I1",
    "O": "slot.O2",
    "SL": "slot.SL2",
    "HD": "slot.HD2",
    "HDx1": "slot.HDx1",
}

# Drawing-output params beyond the registry's "Drawing Parameters" group.
EXTRA_DRAWING_PARAMS: tuple[str, ...] = ("HDx1",)  # distributor HD (4.5)

# Drawing param key -> the template slot whose value the drawing actually renders
# (k=1 representative for per-header slots). The Drawing Parameters panel mirrors
# these so the panel and the template drawing share one source of truth. ZD has no
# slot (unused dimension), so it is intentionally absent.
PARAM_TO_SLOT: dict[str, str] = {
    "CD": "slot.CD",
    "TF": "slot.TF",
    "BF": "slot.BF",
    "HF": "slot.HF",
    "RF": "slot.RF",
    "CH": "slot.CH",
    "HD": "slot.HD2",   # return/suction header HD
    "SL": "slot.SL2",
    "I": "slot.I1",
    "S": "slot.S1",
    "O": "slot.O2",
    "R": "slot.R2",
    "HDx1": "slot.HDx1",  # distributor HD
}

# Params with no header-engine logic (cannot be generated by the engine).
UNCONNECTED_PARAMS: dict[str, str] = {
    "S": "Distributor S position: single-circuit = CD/(circuits+1) (generated below); "
         "multi-circuit is EZ layout geometry -> exact list in Geometry.Headers[].SR.",
}

# ZD (zone depth) is a fixed constant per owner rule (John 2026-06-22), applied to
# every header assembly (ZD, ZD2, ZD3, ...). It is NOT an engine slot or selection
# value -- it is surfaced review-required like every other panel dimension.
ZD_CONSTANT: float = 4.5
ZD_REASON: str = "ZD fixed constant 4.5 (owner rule John 2026-06-22)"

# Logical drawing-parameter bases that repeat per header assembly in the UI grid.
_MULTI_HEADER_BASES: tuple[str, ...] = ("I", "S", "O", "R", "HD")


def _header_slot(base: str, n: int) -> str | None:
    """Logical UI header key base + header index -> engine parity-encoded slot.

    UI header column ``n`` == engine circuit ``n``: the supply/distributor header
    has odd id ``2n-1`` (carries I/S) and the return/suction header has even id
    ``2n`` (carries O/R/HD). This parity<->logical bridge lives ONLY here -- parity
    ids (I3, O4) never leak to the UI, logical ids (I2) never leak to the slots.
    """
    supply_id, return_id = 2 * n - 1, 2 * n
    return {
        "I": f"slot.I{supply_id}",
        "S": f"slot.S{supply_id}",
        "O": f"slot.O{return_id}",
        "R": f"slot.R{return_id}",
        "HD": f"slot.HD{return_id}",
    }.get(base)


# Parity-encoded per-header slot ids the resolver inspects to learn how many header
# assemblies the engine actually produced (so the panel degrades: 1HD -> no extra
# columns, 4HD -> headers 2/3/4 appear only when the engine derived them).
_SLOT_HEADER_RE = re.compile(r"^slot\.(?:I|S|O|R|HD|SL|HDx)(\d+)$")
# Logical multi-header UI key for header assembly n>=2, e.g. "I2", "O3", "ZD4".
_MULTI_HEADER_KEY_RE = re.compile(r"^(?:I|S|O|R|HD|ZD)(\d+)$")


def _max_header_count(slot_values: dict[str, Any]) -> int:
    """Highest header-assembly index present in the parity-encoded slot ids."""
    n_max = 1
    for key in slot_values:
        match = _SLOT_HEADER_RE.match(str(key))
        if match:
            n_max = max(n_max, (int(match.group(1)) + 1) // 2)  # ceil(id/2)
    return n_max


def is_multi_header_param_key(key: str) -> bool:
    """True for a logical header-2+ drawing-parameter key (I2, O3, ZD4, ...)."""
    match = _MULTI_HEADER_KEY_RE.match(str(key))
    return bool(match) and int(match.group(1)) >= 2


def multi_header_logical_values(
    slot_values: dict[str, Any], *, circuits: int | None = None
) -> list[tuple[str, Any]]:
    """Translate parity-encoded per-header slots into logical (key, value) pairs for
    header assemblies n>=2, plus the ``ZD{n}`` constant.

    Header 1 is emitted by the base loops as the unsuffixed I/S/O/R/HD/ZD, so this
    starts at n=2. The header count is inferred from the slots the engine produced;
    an explicit ``circuits`` hint only raises it (never fabricates beyond what the
    engine derived per dimension). A value is ``None`` when the engine did not derive
    that slot -> the panel shows review-required, never a guessed number.
    """
    n_max = _max_header_count(slot_values)
    if circuits:
        n_max = max(n_max, int(circuits))
    pairs: list[tuple[str, Any]] = []
    for n in range(2, n_max + 1):
        for base in _MULTI_HEADER_BASES:
            slot = _header_slot(base, n)
            pairs.append((f"{base}{n}", _coerce_float(slot_values.get(slot)) if slot else None))
        pairs.append((f"ZD{n}", ZD_CONSTANT))
    return pairs


def _casing_height(draft: DirectCoilInputDraft, response: Any) -> float | None:
    """CH = FH + TF + BF (confirmed across all reference cases)."""
    fh = _draft_number(draft, "finned_height")
    if fh is None or "top_flange" not in response.values or "bottom_flange" not in response.values:
        return None
    tf = response.values["top_flange"].value
    bf = response.values["bottom_flange"].value
    if not isinstance(tf, (int, float)) or not isinstance(bf, (int, float)):
        return None
    return round(fh + tf + bf, 4)


def _draft_number(draft: DirectCoilInputDraft, key: str) -> float | None:
    field = draft.fields.get(key)
    if field is None or field.value in (None, ""):
        return None
    try:
        return float(field.value)
    except (TypeError, ValueError):
        return None


def engine_preview_values(
    draft: DirectCoilInputDraft,
    *,
    coil_type: str,
    product_type: str,
    unit_size: str,
    circuits: int | None = None,
    ez_json: dict[str, Any] | None = None,
) -> tuple[list[PreviewDefaultValue], dict[str, Any]]:
    """Return (generated preview values, generation report).

    Reads geometry inputs (rows, feeds, connection size) from the draft and the
    product/size context from the caller (those are not on the Direct Coil form).
    When ``ez_json`` (an EZ Coil export) is supplied, per-header positions are
    taken from its exact as-built ``Headers[].SR`` etc. (handles multi-circuit S).
    """
    rows = _draft_number(draft, "rows_deep")
    feeds = _draft_number(draft, "number_of_feeds")
    conn = _draft_number(draft, "return_connection_size")

    request = build_header_request(
        coil_type=coil_type,
        product_type=product_type,
        unit_size=unit_size,
        rows=int(rows) if rows is not None else None,
        feeds=int(feeds) if feeds is not None else None,
        circuits=circuits,
        suction_conn_size=conn,
    )
    response = prepopulate(request)

    json_slots: dict[str, Any] = {}
    if ez_json:
        from coilforge.services.ez_json_drawing_loader import slots_from_ez_json

        json_slots, _ = slots_from_ez_json(ez_json)

    generated: list[PreviewDefaultValue] = []
    connected: list[str] = []
    json_sourced: list[str] = []
    not_connected: dict[str, str] = {}

    if response.blocked_reason == "unknown_unit_size":
        return [], {
            "source": "rule_engine",
            "status": "blocked",
            "reason": "unknown_unit_size: product_type + unit_size required to generate.",
            "connected": [],
            "not_connected": {k: "engine blocked (unknown unit size)" for k in DRAWING_PARAMETER_KEYS},
        }

    def emit(key: str, value: Any, source: str, reason: str) -> None:
        generated.append(
            PreviewDefaultValue(key=key, value=value, source=source, reason=reason)
        )
        connected.append(key)

    # HDx1 (distributor HD) is a drawing-output param, not a registry field, so
    # it is generated here and injected into the parameter set by the workflow.
    for key in (*DRAWING_PARAMETER_KEYS, *EXTRA_DRAWING_PARAMS):
        # 1. EZ JSON as-built value (exact) takes precedence for per-header positions.
        ez_slot = PARAM_TO_EZ_SLOT.get(key)
        if ez_slot and ez_slot in json_slots:
            emit(key, json_slots[ez_slot], "ez_json/as_built", f"as-built EZ JSON {ez_slot}")
            json_sourced.append(key)
            continue
        # 2. Engine HIGH value.
        engine_field = PARAM_TO_ENGINE_FIELD.get(key)
        if engine_field and engine_field in response.values:
            result = response.values[engine_field]
            emit(key, result.value, "rule_engine/generated",
                 f"engine HIGH value ({engine_field}); evidence {result.evidence_refs[:2]}")
            continue
        # 3. Recovered formulas.
        if key == "R" and conn is not None and circuits:
            emit("R", conn, "rule_engine/generated", "return_spacing[0] = conn size (R-022)")
            continue
        if key == "CH" and (ch := _casing_height(draft, response)) is not None:
            emit("CH", ch, "rule_engine/generated", "CH = FH + TF + BF (CHK CH formula)")
            continue
        if key == "S" and rows is not None and circuits == 1 and "casing_depth" in response.values:
            cd = response.values["casing_depth"].value
            emit("S", round(cd / (circuits + 1), 4), "rule_engine/generated",
                 "S = CD/(circuits+1) (single-circuit distributor center)")
            continue
        if key == "ZD":
            emit("ZD", ZD_CONSTANT, "rule_engine/generated", ZD_REASON)
            continue
        not_connected[key] = UNCONNECTED_PARAMS.get(
            key, f"no engine value (field {engine_field} not HIGH for this coil)"
        )

    # Header assemblies 2..N: translate the engine's parity-encoded per-header slots
    # into logical UI keys (I2/S2/O2/R2/HD2 + ZD2 constant). Sourced from the SAME
    # build_drawing_slots the template drawing renders, so this path and the live
    # template path stay in sync. A local import avoids an import cycle.
    from coilforge.services.direct_coil_drawing_pipeline import build_drawing_slots

    multi_slots, _ = build_drawing_slots(
        coil_type=coil_type,
        product_type=product_type,
        unit_size=unit_size,
        rows=int(rows) if rows is not None else None,
        feeds=int(feeds) if feeds is not None else None,
        circuits=circuits,
        suction_conn_size=conn,
        finned_height=_draft_number(draft, "finned_height"),
        finned_length=_draft_number(draft, "finned_length"),
        ez_json=ez_json,
    )
    for mkey, mvalue in multi_header_logical_values(multi_slots, circuits=circuits):
        if mvalue is None:
            # Engine did not derive this header dimension (e.g. HGRH MEDIUM position
            # gated out). Leave it ungenerated so the report is not misreported as
            # connected; the live panel path still surfaces it as review-required.
            continue
        reason = ZD_REASON if mkey.startswith("ZD") else f"engine-derived header assembly {mkey} (review-required)"
        emit(mkey, mvalue, "rule_engine/generated", reason)

    return generated, {
        "source": "ez_json+rule_engine" if json_sourced else "rule_engine",
        "status": "generated",
        "connected": connected,
        "json_sourced": json_sourced,
        "not_connected": not_connected,
        "review_required": True,
    }


def _coerce_float(value: Any) -> float | None:
    """Numeric slot value (number or numeric string). Anything else -> None."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value.strip())
        except ValueError:
            return None
    return None


def parameter_set_from_template_drawing(
    template_drawing: dict[str, Any], *, circuits: int | None = None
) -> DrawingParameterSet:
    """Build the Drawing Parameters panel from the SAME slot values the template
    drawing renders, so the panel and the drawing never diverge.

    Each panel key maps to its k=1 representative slot (``PARAM_TO_SLOT``). A slot
    carrying a numeric value -> a review-required parameter with that value; a
    missing slot (e.g. the engine is gated until a product line + unit size are
    chosen) -> ``value=None`` so the panel reads review-required, mirroring the
    drawing's REVIEW REQUIRED text. ``HDx1`` (distributor HD) is included so the
    panel shows it alongside ``HD``. ``ZD`` is the owner-fixed constant 4.5.

    Header assemblies 2..N (logical ``I2/S2/O2/R2/HD2/ZD2`` ...) are appended for
    multi-circuit coils by translating the engine's parity-encoded per-header slots
    (``multi_header_logical_values``). The count is inferred from the slots present;
    an explicit ``circuits`` hint only raises it. 1HD coils get no extra header keys.
    """
    slot_values = (template_drawing or {}).get("slot_values") or {}

    parameters: dict[str, DrawingParameter] = {}
    review_required: list[str] = []
    blocked: list[str] = []

    for key in (*DRAWING_PARAMETER_KEYS, *EXTRA_DRAWING_PARAMS):
        if key == "ZD":
            # ZD is the owner-fixed constant (no engine slot); surface review-required.
            parameters[key] = DrawingParameter(
                key=key, label=key, value=ZD_CONSTANT, unit="in",
                mode="default", status="review_required", review_required=True,
            )
            review_required.append(key)
            continue
        slot = PARAM_TO_SLOT.get(key)
        if slot is None:
            # No slot for this dimension: unmapped, as before.
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="unmapped", status="unmapped", review_required=False,
            )
            continue
        value = _coerce_float(slot_values.get(slot))
        if value is None:
            # Mappable, but the drawing has not derived it yet (engine gated).
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="blocked", status="review_required", review_required=True,
                blocked_reason="Pick a product line + unit size to derive this dimension.",
            )
            review_required.append(key)
            continue
        parameters[key] = DrawingParameter(
            key=key, label=key, value=value, unit="in",
            mode="default", status="review_required", review_required=True,
        )
        review_required.append(key)

    # Header assemblies 2..N (logical I2/S2/O2/R2/HD2/ZD2, ...). The parity<->logical
    # bridge and degrade-to-present logic live in multi_header_logical_values.
    for key, value in multi_header_logical_values(slot_values, circuits=circuits):
        if value is None and not key.startswith("ZD"):
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="blocked", status="review_required", review_required=True,
                blocked_reason="Engine did not derive this header dimension; review required.",
            )
        else:
            parameters[key] = DrawingParameter(
                key=key, label=key, value=value, unit="in",
                mode="default", status="review_required", review_required=True,
            )
        review_required.append(key)

    return DrawingParameterSet(
        parameters=parameters,
        preview_allowed=True,
        export_allowed=False,
        blocked_parameters=blocked,
        review_required_parameters=review_required,
        required_preview_parameters=list(REQUIRED_PREVIEW_PARAMETER_KEYS),
        notes=["Panel mirrors the template drawing's slot values (review-aid only)."],
    )
