"""Generate drawing preview parameters from the header rule engine.

Replaces the hardcoded ``DEFAULT_PREVIEW_VALUES`` demo constants with values
generated from the actual coil inputs by the header-prepopulation engine.

Drawing parameter set (DIRECT_COIL_FIELD_REGISTRY "Drawing Parameters"):
    CD, I, S, O, R, BF, HD, HF, TF, RF, CH, SL, ZD

Mapping status (DX):
    GENERATED (HIGH engine value):  CD, TF, BF, HF, RF, HD, SL, I, O, S (R-034 even-spacing),
                                    CH (= FH + TF + BF), (R when circuits+conn known)
    CONSTANT (owner rule):          ZD = 4.5 (and ZD{n})
    INPUT-GATED (blank only when the input is missing): R (return conn size), CH (FH), CD (rows)
Header assemblies 2..N (I2/S2/O2/R2/HD2/ZD2 ...) are translated from the engine's
parity-encoded per-header slots; see multi_header_logical_values.
Only HIGH engine values are emitted as generated; MEDIUM/blocked stay review.
"""

from __future__ import annotations

import re
from functools import lru_cache
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from coilforge.direct_coil.draft import DirectCoilInputDraft
from coilforge.drawing.parameters import (
    DRAWING_PARAMETER_KEYS,
    REQUIRED_PREVIEW_PARAMETER_KEYS,
    DrawingParameter,
    DrawingParameterOverride,
    DrawingParameterSet,
    PreviewDefaultValue,
)
from coilforge.services.direct_coil_drawing_pipeline import build_header_request
from coilforge.services.header_prepopulate_engine import prepopulate, round_eighth
from coilforge.submittal.coilmaster_drawing_extract import (
    product_size_options,
    resolve_product_line,
)

# Drawing param key -> scalar engine field (HIGH values).
PARAM_TO_ENGINE_FIELD: dict[str, str] = {
    "CD": "casing_depth",
    "TF": "top_flange",
    "BF": "bottom_flange",
    "HF": "header_flange",
    "RF": "return_flange",
    "HD": "suction_hd",   # return/suction header HD (3.5)
    "HDx1": "dist_hd",    # distributor header HD (4.5)
    "SL": "suction_sl",
    "I": "dist_i",        # DX distributor I
    "O": "suction_io",    # DX return I/O
}

# Drawing param key -> EZ JSON slot id (from ez_json_drawing_loader). When an EZ
# export is present these exact as-built values override the engine predictions
# for per-header positions (handles multi-circuit S, etc.).
PARAM_TO_EZ_SLOT: dict[str, str] = {
    "S": "slot.S1",      # Geometry.Headers[supply].SR (exact)
    "R": "slot.R2",      # Geometry.Headers[return].SR
    "I": "slot.I1",
    "O": "slot.O2",
    "SL": "slot.SL2",
    "HD": "slot.HD2",
    "HDx1": "slot.HDx1",
}

# Drawing-output params beyond the registry's "Drawing Parameters" group.
EXTRA_DRAWING_PARAMS: tuple[str, ...] = ("HDx1",)  # distributor HD (4.5)

# Drawing param key -> the template slot whose value the drawing actually renders
# (k=1 representative for per-header slots). The Drawing Parameters panel mirrors
# these so the panel and the template drawing share one source of truth. ZD has no
# slot (unused dimension), so it is intentionally absent.
PARAM_TO_SLOT: dict[str, str] = {
    "CD": "slot.CD",
    "TF": "slot.TF",
    "BF": "slot.BF",
    "HF": "slot.HF",
    "RF": "slot.RF",
    "CH": "slot.CH",
    "HD": "slot.HD2",   # return/suction header HD
    "SL": "slot.SL2",
    "I": "slot.I1",
    "S": "slot.S1",
    "O": "slot.O2",
    "R": "slot.R2",
    "HDx1": "slot.HDx1",  # distributor HD
}

# Reason strings for the not_connected fallback (used only when the input needed to run
# the wired formula is missing). S is generated by R-034 (below) for header 1 at any circuit
# count; headers 2+ come from build_drawing_slots. EZ JSON is an exact OVERRIDE, not the only
# source. This entry names the missing input when S can't be computed.
UNCONNECTED_PARAMS: dict[str, str] = {
    "S": "Distributor S (R-034 even-spacing = ROUND(k*CD/(circuits+1)*8,0)/8): needs the circuit "
         "count + casing depth; header 1 is generated when both are known, headers 2+ come "
         "from the slot layer.",
}

# When a product line + unit size ARE chosen (the engine ran) but a dimension slot is
# still empty, the generic "pick a product line" message is misleading. These reasons
# name the actual missing input so a blank reads as "what to supply", not "is it broken".
# R = return spacing = circuits*conn + (circuits-1)*1.5, so it needs the return conn size.
_BLANK_REASON_AFTER_PRODUCT: dict[str, str] = {
    "R": "Needs the return connection size — not found in the submittal extract.",
}

# Per-(coil category, key) override. The generic R message names the connection size, which
# is right for DX/HGRH but was a MISDIAGNOSIS on water coils (John 2026-07-28): a water
# coil's connection size IS extracted (Inlet/Outlet Conn. Size), and water R mirrors the
# supply spacing S rather than the connection size at all. Sending the engineer to hunt for
# a value that is already present is worse than saying nothing.
_BLANK_REASON_BY_CATEGORY: dict[tuple[str, str], str] = {
    (category, "R"): (
        "Water-coil R mirrors the supply spacing S, and S is the connection size — "
        "no connection size was read from the submittal."
    )
    for category in ("CWC", "HWC")
}

# Per-(coil category, terra variant, key BASE) reason for a value the engine could have
# written and DELIBERATELY did not. Distinct in kind from the two maps above, which
# describe a missing INPUT: these say "no rule covers this position, so nothing was
# invented". Without them the panel falls back to "Engine did not derive this
# dimension", which reads as a bug on a value withheld on SOP grounds — and Phase C
# then paints it red with no explanation. Keyed on the base letter so every header
# index (I2/I3/I4) inherits the same reason.
_WITHHELD_REASON_BY_VARIANT: dict[tuple[str, str, str], str] = {
    ("HGRH", "TERRA_V", "I"): (
        "Terra V HGRH Supply I/O is SOP-confirmed for Supply 1 only (R-046); Supply 2+ "
        "is a software default, not derivable — fill it in if the drawing needs it. "
        "(The Return I/O beside it IS filled on every header: R-042v states 2.75 for all "
        "Terra V returns, so the two are not inconsistent — one rule covers every "
        "position, the other only the first.)"
    ),
    ("HGRH", "TERRA_V", "S"): (
        "Terra V HGRH supply spacing is S = CD − Rn (SOP), and Rn only runs to the "
        "connections-per-header count — this header has no Rn to subtract."
    ),
}

_KEY_BASE_RE = re.compile(r"^([A-Za-z]+)")


def _key_base(key: str) -> str:
    """Panel key -> its letter base ("I2" -> "I", "HDx1" -> "HDx", "CD" -> "CD")."""
    m = _KEY_BASE_RE.match(key or "")
    return m.group(1) if m else (key or "")


#: Terra V HGRH supply spacing has TWO distinct withholding causes and the map above can
#: hold only one -- ``_key_base`` folds S1/S2/S3 onto "S". They are told apart from the
#: slot values themselves rather than through a new reason channel: the header's return
#: spacing is either absent (no Rn to subtract) or present but past the casing depth.
_TERRA_V_S_BEYOND_CASING = (
    "Terra V HGRH supply spacing is S = CD − Rn (SOP), and this header's Rn has passed "
    "the casing depth — the formula is outside its premise here, so no value is drawn "
    "rather than a negative one. Terra V CD is rows-based and does not grow with the "
    "header count; confirm the connections-per-header count."
)


def _terra_v_s_beyond_casing(key: str, slot_values: dict[str, Any] | None) -> bool:
    """True when this Terra V HGRH supply S was withheld because ``Rn >= CD``."""
    if not slot_values:
        return False
    slot = slot_for_param_key(key)
    if not slot:
        return False
    m = re.match(r"^slot\.S(\d+)$", slot)
    if not m:
        return False
    rn = _coerce_float(slot_values.get(f"slot.R{int(m.group(1)) + 1}"))
    cd = _coerce_float(slot_values.get("slot.CD"))
    return rn is not None and cd is not None and rn >= cd


def _blank_reason(
    key: str,
    *,
    coil_category: str,
    terra_variant: str | None,
    product_chosen: bool,
    slot_values: dict[str, Any] | None = None,
) -> str:
    """The message a blank drawing-parameter row shows in place of a number.

    Order matters: a DELIBERATE withholding outranks the generic "missing input"
    wording, because the two send the engineer to different places (supply the value
    vs. hunt for a submittal field that was never going to exist).
    """
    if not product_chosen:
        return "Pick a product line + unit size to derive this dimension."
    variant = (terra_variant or "").upper()
    base = _key_base(key)
    if (
        coil_category == "HGRH"
        and variant == "TERRA_V"
        and base == "S"
        and _terra_v_s_beyond_casing(key, slot_values)
    ):
        return _TERRA_V_S_BEYOND_CASING
    withheld = _WITHHELD_REASON_BY_VARIANT.get((coil_category, variant, base))
    if withheld:
        return withheld
    return _BLANK_REASON_BY_CATEGORY.get(
        (coil_category, key)
    ) or _BLANK_REASON_AFTER_PRODUCT.get(
        key, "Engine did not derive this dimension; review required."
    )

# ZD (zone depth) is a fixed constant per owner rule (John 2026-06-22), applied to
# every header assembly (ZD, ZD2, ZD3, ...). It is NOT an engine slot or selection
# value -- it is surfaced review-required like every other panel dimension.
ZD_CONSTANT: float = 4.5
ZD_REASON: str = "ZD fixed constant 4.5 (owner rule John 2026-06-22)"

# Logical drawing-parameter bases that repeat per header assembly in the UI grid.
_MULTI_HEADER_BASES: tuple[str, ...] = ("I", "S", "O", "R", "HD")


def _header_slot(base: str, n: int) -> str | None:
    """Logical UI header key base + header index -> engine parity-encoded slot.

    UI header column ``n`` == engine circuit ``n``: the supply/distributor header
    has odd id ``2n-1`` (carries I/S) and the return/suction header has even id
    ``2n`` (carries O/R/HD). This parity<->logical bridge lives ONLY here -- parity
    ids (I3, O4) never leak to the UI, logical ids (I2) never leak to the slots.
    """
    supply_id, return_id = 2 * n - 1, 2 * n
    return {
        "I": f"slot.I{supply_id}",
        "S": f"slot.S{supply_id}",
        "O": f"slot.O{return_id}",
        "R": f"slot.R{return_id}",
        "HD": f"slot.HD{return_id}",
    }.get(base)


def slot_for_param_key(key: str) -> str | None:
    """Drawing-parameter key -> engine slot id (base keys AND logical multi-header keys).

    The single place that answers "which slot does this panel row render?". Base keys
    (and ``HDx1``, which carries digits, hence the direct lookup first) come from
    ``PARAM_TO_SLOT``; a logical multi-header key (``S2``, ``O3``) goes through
    ``_header_slot`` for the logical->parity bridge. ``ZD``/``ZD2`` have no slot.

    Hoisted out of ``checklist/overrides.param_slot`` (which now delegates) so the
    checklist comparison, the Tier-B override path and the panel all resolve a row's
    slot identically — that shared answer is what lets the checklist's per-dim verdicts
    be joined onto the panel by slot rather than by an ambiguous label.
    """
    key = str(key)
    if key in PARAM_TO_SLOT:
        return PARAM_TO_SLOT[key]
    base = key.rstrip("0123456789")
    digits = key[len(base):]
    if base and digits:
        try:
            n = int(digits)
        except ValueError:
            return None
        if n >= 2:
            return _header_slot(base, n)
    return None


@lru_cache(maxsize=1)
def _slot_to_param_key() -> dict[str, str]:
    """Inverse of :func:`slot_for_param_key`, for the panel keys only.

    Header 1 comes from ``PARAM_TO_SLOT``; headers 2..8 from ``_header_slot``. No
    collisions: ``_header_slot`` is only consulted for n>=2, so ``slot.O2`` belongs to
    the bare ``O`` and never to a numbered key.
    """
    inverse = {slot: key for key, slot in PARAM_TO_SLOT.items()}
    for n in range(2, 9):
        for base in _MULTI_HEADER_BASES:
            slot = _header_slot(base, n)
            if slot and slot not in inverse:
                inverse[slot] = f"{base}{n}"
    return inverse


def param_key_for_slot(slot: str | None) -> str | None:
    """Engine slot id -> the drawing-parameter key the panel shows it under.

    Needed wherever a slot-addressed record has to line up with something keyed by
    panel key — the correction ledger, for one, stores ``field_key`` as the panel key,
    so a checklist observation filed under the SHEET's label (``S1``, ``O4``) would
    never join the correction that followed it.
    """
    return _slot_to_param_key().get(str(slot)) if slot else None


# Parity-encoded per-header slot ids the resolver inspects to learn how many header
# assemblies the engine actually produced (so the panel degrades: 1HD -> no extra
# columns, 4HD -> headers 2/3/4 appear only when the engine derived them).
_SLOT_HEADER_RE = re.compile(r"^slot\.(?:I|S|O|R|HD|SL|HDx)(\d+)$")
# Logical multi-header UI key for header assembly n>=2, e.g. "I2", "O3", "ZD4".
_MULTI_HEADER_KEY_RE = re.compile(r"^(?:I|S|O|R|HD|ZD)(\d+)$")


def _max_header_count(slot_values: dict[str, Any]) -> int:
    """Highest header-assembly index present in the parity-encoded slot ids."""
    n_max = 1
    for key in slot_values:
        match = _SLOT_HEADER_RE.match(str(key))
        if match:
            n_max = max(n_max, (int(match.group(1)) + 1) // 2)  # ceil(id/2)
    return n_max


def is_multi_header_param_key(key: str) -> bool:
    """True for a logical header-2+ drawing-parameter key (I2, O3, ZD4, ...)."""
    match = _MULTI_HEADER_KEY_RE.match(str(key))
    return bool(match) and int(match.group(1)) >= 2


def multi_header_logical_values(
    slot_values: dict[str, Any], *, circuits: int | None = None
) -> list[tuple[str, Any]]:
    """Translate parity-encoded per-header slots into logical (key, value) pairs for
    header assemblies n>=2, plus the ``ZD{n}`` constant.

    Header 1 is emitted by the base loops as the unsuffixed I/S/O/R/HD/ZD, so this
    starts at n=2. The header count is inferred from the slots the engine produced;
    an explicit ``circuits`` hint only raises it (never fabricates beyond what the
    engine derived per dimension). A value is ``None`` when the engine did not derive
    that slot -> the panel shows review-required, never a guessed number.
    """
    n_max = _max_header_count(slot_values)
    if circuits:
        n_max = max(n_max, int(circuits))
    pairs: list[tuple[str, Any]] = []
    for n in range(2, n_max + 1):
        for base in _MULTI_HEADER_BASES:
            slot = _header_slot(base, n)
            pairs.append((f"{base}{n}", _coerce_float(slot_values.get(slot)) if slot else None))
        pairs.append((f"ZD{n}", ZD_CONSTANT))
    return pairs


def _casing_height(draft: DirectCoilInputDraft, response: Any) -> float | None:
    """CH = FH + TF + BF (confirmed across all reference cases)."""
    fh = _draft_number(draft, "finned_height")
    if fh is None or "top_flange" not in response.values or "bottom_flange" not in response.values:
        return None
    tf = response.values["top_flange"].value
    bf = response.values["bottom_flange"].value
    if not isinstance(tf, (int, float)) or not isinstance(bf, (int, float)):
        return None
    return round(fh + tf + bf, 4)


def _draft_number(draft: DirectCoilInputDraft, key: str) -> float | None:
    field = draft.fields.get(key)
    if field is None or field.value in (None, ""):
        return None
    try:
        return float(field.value)
    except (TypeError, ValueError):
        return None


def engine_preview_values(
    draft: DirectCoilInputDraft,
    *,
    coil_type: str,
    product_type: str,
    unit_size: str,
    circuits: int | None = None,
    ez_json: dict[str, Any] | None = None,
) -> tuple[list[PreviewDefaultValue], dict[str, Any]]:
    """Return (generated preview values, generation report).

    Reads geometry inputs (rows, feeds, connection size) from the draft and the
    product/size context from the caller (those are not on the Direct Coil form).
    When ``ez_json`` (an EZ Coil export) is supplied, per-header positions are
    taken from its exact as-built ``Headers[].SR`` etc. (handles multi-circuit S).
    """
    rows = _draft_number(draft, "rows_deep")
    feeds = _draft_number(draft, "number_of_feeds")
    conn = _draft_number(draft, "return_connection_size")
    qty_conn = _draft_number(draft, "qty_connections_per_header")
    qty_conn_per_header = int(qty_conn) if qty_conn is not None else None
    # HGRH names its single connection `conn_size` (R-048 positions, R-052 return
    # spacing); DX uses `suction_conn_size`. Route the read connection size to the
    # field this coil category's rules consume so HGRH "R" can resolve.
    is_hgrh = str(coil_type or "").strip().upper() == "HGRH"
    conn_size = conn if is_hgrh else None

    request = build_header_request(
        coil_type=coil_type,
        product_type=product_type,
        unit_size=unit_size,
        rows=int(rows) if rows is not None else None,
        feeds=int(feeds) if feeds is not None else None,
        circuits=circuits,
        suction_conn_size=conn,
        conn_size=conn_size,
        qty_conn_per_header=qty_conn_per_header,
    )
    response = prepopulate(request)

    json_slots: dict[str, Any] = {}
    if ez_json:
        from coilforge.services.ez_json_drawing_loader import slots_from_ez_json

        json_slots, _ = slots_from_ez_json(ez_json)

    generated: list[PreviewDefaultValue] = []
    connected: list[str] = []
    json_sourced: list[str] = []
    not_connected: dict[str, str] = {}

    if response.blocked_reason == "unknown_unit_size":
        return [], {
            "source": "rule_engine",
            "status": "blocked",
            "reason": "unknown_unit_size: product_type + unit_size required to generate.",
            "connected": [],
            "not_connected": {k: "engine blocked (unknown unit size)" for k in DRAWING_PARAMETER_KEYS},
        }

    def emit(key: str, value: Any, source: str, reason: str) -> None:
        generated.append(
            PreviewDefaultValue(key=key, value=value, source=source, reason=reason)
        )
        connected.append(key)

    # HDx1 (distributor HD) is a drawing-output param, not a registry field, so
    # it is generated here and injected into the parameter set by the workflow.
    for key in (*DRAWING_PARAMETER_KEYS, *EXTRA_DRAWING_PARAMS):
        # 1. EZ JSON as-built value (exact) takes precedence for per-header positions.
        ez_slot = PARAM_TO_EZ_SLOT.get(key)
        if ez_slot and ez_slot in json_slots:
            emit(key, json_slots[ez_slot], "ez_json/as_built", f"as-built EZ JSON {ez_slot}")
            json_sourced.append(key)
            continue
        # 2. Engine HIGH value.
        engine_field = PARAM_TO_ENGINE_FIELD.get(key)
        if engine_field and engine_field in response.values:
            result = response.values[engine_field]
            emit(key, result.value, "rule_engine/generated",
                 f"engine HIGH value ({engine_field}); evidence {result.evidence_refs[:2]}")
            continue
        # 3. Recovered formulas.
        if key == "R" and conn is not None and circuits:
            emit("R", conn, "rule_engine/generated", "return_spacing[0] = conn size (R-022)")
            continue
        if key == "CH" and (ch := _casing_height(draft, response)) is not None:
            emit("CH", ch, "rule_engine/generated", "CH = FH + TF + BF (CHK CH formula)")
            continue
        if key == "S" and circuits and "casing_depth" in response.values:
            cd = response.values["casing_depth"].value
            emit("S", round_eighth(cd / (circuits + 1)), "rule_engine/generated",
                 "S = ROUND(CD/(circuits+1)*8,0)/8 (R-034 even-spacing snapped to the "
                 "nearest 1/8 per CHK DX!C46, header-1 distributor center)")
            continue
        if key == "ZD":
            emit("ZD", ZD_CONSTANT, "rule_engine/generated", ZD_REASON)
            continue
        not_connected[key] = UNCONNECTED_PARAMS.get(
            key, f"no engine value (field {engine_field} not HIGH for this coil)"
        )

    # Header assemblies 2..N: translate the engine's parity-encoded per-header slots
    # into logical UI keys (I2/S2/O2/R2/HD2 + ZD2 constant). Sourced from the SAME
    # build_drawing_slots the template drawing renders, so this path and the live
    # template path stay in sync. A local import avoids an import cycle.
    from coilforge.services.direct_coil_drawing_pipeline import build_drawing_slots

    multi_slots, _ = build_drawing_slots(
        coil_type=coil_type,
        product_type=product_type,
        unit_size=unit_size,
        rows=int(rows) if rows is not None else None,
        feeds=int(feeds) if feeds is not None else None,
        circuits=circuits,
        suction_conn_size=conn,
        conn_size=conn_size,
        qty_conn_per_header=qty_conn_per_header,
        finned_height=_draft_number(draft, "finned_height"),
        finned_length=_draft_number(draft, "finned_length"),
        ez_json=ez_json,
    )
    for mkey, mvalue in multi_header_logical_values(multi_slots, circuits=circuits):
        if mvalue is None:
            # Engine did not derive this header dimension (e.g. HGRH MEDIUM position
            # gated out). Leave it ungenerated so the report is not misreported as
            # connected; the live panel path still surfaces it as review-required.
            continue
        reason = ZD_REASON if mkey.startswith("ZD") else f"engine-derived header assembly {mkey} (review-required)"
        emit(mkey, mvalue, "rule_engine/generated", reason)

    return generated, {
        "source": "ez_json+rule_engine" if json_sourced else "rule_engine",
        "status": "generated",
        "connected": connected,
        "json_sourced": json_sourced,
        "not_connected": not_connected,
        "review_required": True,
    }


def _coerce_float(value: Any) -> float | None:
    """Numeric slot value (number or numeric string). Anything else -> None."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value.strip())
        except ValueError:
            return None
    return None


def parameter_set_from_template_drawing(
    template_drawing: dict[str, Any],
    *,
    circuits: int | None = None,
    param_overrides: list[DrawingParameterOverride | dict[str, Any]] | None = None,
) -> DrawingParameterSet:
    """Build the Drawing Parameters panel from the SAME slot values the template
    drawing renders, so the panel and the drawing never diverge.

    Each panel key maps to its k=1 representative slot (``PARAM_TO_SLOT``). A slot
    carrying a numeric value -> a review-required parameter with that value; a
    missing slot (e.g. the engine is gated until a product line + unit size are
    chosen) -> ``value=None`` so the panel reads review-required, mirroring the
    drawing's REVIEW REQUIRED text. ``HDx1`` (distributor HD) is included so the
    panel shows it alongside ``HD``. ``ZD`` is the owner-fixed constant 4.5.

    Header assemblies 2..N (logical ``I2/S2/O2/R2/HD2/ZD2`` ...) are appended for
    multi-circuit coils by translating the engine's parity-encoded per-header slots
    (``multi_header_logical_values``). The count is inferred from the slots present;
    an explicit ``circuits`` hint only raises it. 1HD coils get no extra header keys.
    """
    slot_values = (template_drawing or {}).get("slot_values") or {}
    # Did the engineer already pick a product line + unit size? If so the engine has
    # run and an empty slot is a missing *input* (e.g. connection size), not "pick a
    # product line"; choose a reason that names the real gap (see _BLANK_REASON...).
    td = template_drawing or {}
    product_chosen = bool(td.get("product_type") and td.get("unit_size"))
    coil_category = str((td.get("extracted") or {}).get("coil_category") or "").upper()
    # Terra variant is DERIVED here, not threaded in: no caller has it (grep for
    # terra_variant across this module, submittal_to_drawing and pdf_to_template_drawing
    # returns nothing), and one of the four call sites is capture/record.py, which builds
    # the correction ledger's pristine baseline through this same function — a threaded
    # argument that call site forgot would make the baseline's blocked_reason silently
    # disagree with the live panel.
    _, terra_variant = resolve_product_line(td.get("product_type"))

    parameters: dict[str, DrawingParameter] = {}
    review_required: list[str] = []
    blocked: list[str] = []

    for key in (*DRAWING_PARAMETER_KEYS, *EXTRA_DRAWING_PARAMS):
        if key == "ZD":
            # ZD is the owner-fixed constant (no engine slot); surface review-required.
            parameters[key] = DrawingParameter(
                key=key, label=key, value=ZD_CONSTANT, unit="in",
                mode="default", status="review_required", review_required=True,
            )
            review_required.append(key)
            continue
        slot = PARAM_TO_SLOT.get(key)
        if slot is None:
            # No slot for this dimension: unmapped, as before.
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="unmapped", status="unmapped", review_required=False,
            )
            continue
        value = _coerce_float(slot_values.get(slot))
        if value is None:
            # Mappable, but the drawing has not derived it yet. Before a product line +
            # unit size are chosen the engine is gated; after, an empty slot is a missing
            # input — name it so the blank explains itself instead of reading as a bug.
            reason = _blank_reason(
                key,
                coil_category=coil_category,
                terra_variant=terra_variant,
                product_chosen=product_chosen,
                slot_values=slot_values,
            )
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="blocked", status="review_required", review_required=True,
                blocked_reason=reason,
            )
            review_required.append(key)
            continue
        parameters[key] = DrawingParameter(
            key=key, label=key, value=value, unit="in",
            mode="default", status="review_required", review_required=True,
        )
        review_required.append(key)

    # Header assemblies 2..N (logical I2/S2/O2/R2/HD2/ZD2, ...). The parity<->logical
    # bridge and degrade-to-present logic live in multi_header_logical_values.
    for key, value in multi_header_logical_values(slot_values, circuits=circuits):
        if value is None and not key.startswith("ZD"):
            # Consults the SAME reason lookup as the base loop above. It used to hardcode
            # its message, so a deliberately-withheld multi-header value (Terra V HGRH I2+)
            # was indistinguishable from an engine that simply failed.
            parameters[key] = DrawingParameter(
                key=key, label=key, value=None, unit="in",
                mode="blocked", status="review_required", review_required=True,
                blocked_reason=_blank_reason(
                    key,
                    coil_category=coil_category,
                    terra_variant=terra_variant,
                    product_chosen=product_chosen,
                    slot_values=slot_values,
                ),
            )
        else:
            parameters[key] = DrawingParameter(
                key=key, label=key, value=value, unit="in",
                mode="default", status="review_required", review_required=True,
            )
        review_required.append(key)

    # Tier-B manual overrides: a user-supplied value wins over the derived/blank slot
    # value for that key. Stays review-required + manual_override — never promoted to
    # HIGH/confirmed, export_allowed stays False. This block sets the PANEL value; the
    # non-frozen caller (_reflect_param_overrides_into_slots, 1b) also merges the same
    # override into slot_values and re-populates the SVG so the drawing reflects it
    # (John 2026-07-16 — reverses the earlier panel-only rule; still review-aid only).
    override_notes: list[str] = []
    for override in (
        DrawingParameterOverride.model_validate(item) for item in (param_overrides or [])
    ):
        if override.value in (None, ""):
            continue
        parameters[override.key] = DrawingParameter(
            key=override.key,
            label=override.key,
            value=override.value,
            unit=override.unit or "in",
            mode="manual",
            source_evidence=list(override.source_evidence),
            status="review_required",
            review_required=True,
            blocked_reason=None,
            manual_override=True,
        )
        if override.key not in review_required:
            review_required.append(override.key)
        override_notes = ["Manual override params are review-required; reflected into the drawing by the non-frozen caller (never HIGH/export-approved)."]

    return DrawingParameterSet(
        parameters=parameters,
        preview_allowed=True,
        export_allowed=False,
        blocked_parameters=blocked,
        review_required_parameters=review_required,
        required_preview_parameters=list(REQUIRED_PREVIEW_PARAMETER_KEYS),
        notes=["Panel mirrors the template drawing's slot values (review-aid only)."]
        + override_notes,
    )


# --------------------------------------------------------------------------- #
# Manual-fill plan (human-in-the-loop): what the engineer can fill to complete
# the drawing, surfaced automatically when a coil is blocked/missing data.
# --------------------------------------------------------------------------- #

# Engine inputs the engineer can supply to un-gate the rule engine. label + unit
# for the panel; only these known-fillable inputs are surfaced (a missing_input
# token not in this map is left to show as a blocked dimension, not a fill field).
_ENGINE_INPUT_META: dict[str, tuple[str, str]] = {
    "rows": ("Rows deep", ""),
    "feeds": ("Number of feeds", ""),
    "circuits": ("Circuits", ""),
    "suction_conn_size": ("Suction/return connection size", "in"),
    "conn_size": ("Connection size", "in"),
    "qty_conn_per_header": ("Connections per header", ""),
    "application": ("Application (casing class)", ""),
    "header_count": ("Header count (1HD–4HD)", ""),
}


class ManualFillItem(BaseModel):
    """One thing the engineer can fill to complete the drawing. ``kind`` routes the
    UI widget (engine input vs. a direct drawing-param override) and ``allowed``
    (when present) turns it into a picker (product line / unit size)."""

    model_config = ConfigDict(extra="forbid")

    key: str
    # "template_input" is neither an engine input nor a dimension override: it re-selects
    # the TEMPLATE (coil hand picks the LH vs RH artwork). It routes separately in the UI
    # because filling it redraws from a different template rather than recomputing slots.
    kind: Literal["engine_input", "drawing_param", "template_input"]
    label: str
    reason: str
    allowed: list[Any] = Field(default_factory=list)
    current_value: Any = None
    unit: str = "in"


class ManualFillPlan(BaseModel):
    """The auto-surfaced 'fill these to complete the drawing' list for one coil.
    ``withheld_reason`` is set (and ``items`` empty) when the drawing is gate-omitted
    — filling cannot un-gate it, so no fill inputs are offered."""

    model_config = ConfigDict(extra="forbid")

    items: list[ManualFillItem] = Field(default_factory=list)
    withheld_reason: str | None = None


def build_manual_fill_plan(
    template_drawing: dict[str, Any],
    response: Any = None,
    param_set: DrawingParameterSet | None = None,
) -> ManualFillPlan:
    """Assemble the human-in-the-loop fill plan for one coil's drawing.

    Sources (all read-only against the already-built drawing/panel):
    - product/unit-size picker when no product line is chosen (the normal gated
      state, not an error — so surfaced unconditionally, with ``allowed``);
    - engine-input items from ``response.missing_inputs`` (or, when no engine
      response is available, parsed from ``template_drawing['review_items']``),
      filtered to the known-fillable un-gate levers;
    - drawing-param items for panel params the engine left blocked (``mode=='blocked'``);
    - a ``withheld_reason`` instead of fill inputs when the drawing is gate-omitted.

    Never invents a value — every item names WHAT to supply and WHY, review-aid only.
    """
    td = template_drawing or {}

    # Gate-omit: the drawing is withheld regardless of fills (unseeded Ventum+ DX,
    # unsupported HGBP line). Do NOT present its dims as fillable — filling cannot
    # un-gate it.
    withheld = td.get("not_registered_reason")
    if withheld:
        return ManualFillPlan(items=[], withheld_reason=str(withheld))

    items: list[ManualFillItem] = []
    seen: set[str] = set()

    # Coil hand picker — offered whenever a drawing exists, NOT only when the hand was
    # assumed. Gating it on `coil_hand_defaulted` made the lever vanish the moment the
    # engineer supplied a hand, so a mis-click (RH -> LH) could not be undone: the fill
    # that set it also removed the only control for changing it (John 2026-07-29).
    # It is a legitimate standing correction either way — a MISREAD hand is as damaging
    # as a missing one, because the hand selects the LH vs RH template and therefore
    # mirrors the entire drawing.
    if td.get("svg"):
        items.append(
            ManualFillItem(
                key="coil_hand", kind="template_input", label="Coil hand",
                reason=str(
                    td.get("coil_hand_review")
                    or "Coil hand selects the LH vs RH template — it mirrors the whole "
                       "drawing. Change it if the hand read from the submittal is wrong."
                ),
                allowed=["Left", "Right"],
                # Normalised into the picker's own vocabulary: the resolved hand is "LH"/
                # "RH" when it came from the drawing path but "Left"/"Right" when it came
                # from a manual fill, and a current_value outside `allowed` leaves the
                # picker with nothing selected.
                current_value={"LH": "Left", "RH": "Right"}.get(
                    str((td.get("extracted") or {}).get("hand") or "").upper(),
                    (td.get("extracted") or {}).get("hand"),
                ),
                unit="",
            )
        )
        seen.add("coil_hand")

    # An invalid (not merely absent) unit_size — the engine returned unknown_unit_size —
    # also needs the picker, even though product_type/unit_size are both truthy.
    bad_unit_size = (
        response is not None
        and getattr(response, "blocked_reason", None) == "unknown_unit_size"
    )

    # Product / unit-size picker — the HEADLINE "no product line" case. product_chosen
    # is recomputed from the top-level result keys (the resolver's local is not exposed).
    product_type = td.get("product_type")
    unit_size = td.get("unit_size")
    if not (product_type and unit_size) or bad_unit_size:
        opts = product_size_options()
        if not product_type:
            items.append(
                ManualFillItem(
                    key="product_type", kind="engine_input", label="Product line",
                    reason="Pick a product line to derive dimensions.",
                    allowed=sorted(opts.keys()), current_value=product_type,
                )
            )
            seen.add("product_type")
        if not unit_size or bad_unit_size:
            sizes = (
                list(opts.get(product_type, []))
                if product_type
                else sorted({s for group in opts.values() for s in group})
            )
            reason = (
                f"'{unit_size}' is not a valid unit size for this product — pick one."
                if bad_unit_size
                else "Pick a unit size to derive dimensions."
            )
            items.append(
                ManualFillItem(
                    key="unit_size", kind="engine_input", label="Unit size",
                    reason=reason, allowed=sizes, current_value=unit_size,
                )
            )
            seen.add("unit_size")

    # Engine inputs the engineer can supply to un-gate cascades. Prefer the live
    # response's missing_inputs; fall back to parsing the review_items strings.
    missing_inputs: list[str] = []
    if response is not None and getattr(response, "missing_inputs", None):
        missing_inputs = list(response.missing_inputs)
    else:
        for raw in td.get("review_items") or []:
            text = str(raw)
            if text.startswith("missing_input:"):
                missing_inputs.append(text.split(":", 1)[1].strip())
    for inp in missing_inputs:
        if inp in seen or inp not in _ENGINE_INPUT_META:
            continue
        seen.add(inp)
        label, unit = _ENGINE_INPUT_META[inp]
        items.append(
            ManualFillItem(
                key=inp, kind="engine_input", label=label,
                reason="Required by the rule engine to derive dimensions — supply to un-gate.",
                unit=unit or "in",
            )
        )

    # Drawing-param items: panel params the engine left blocked (mode=='blocked' ONLY —
    # NOT value is None, which also matches 'unmapped' non-fillable rows).
    if param_set is not None:
        for key, parameter in param_set.parameters.items():
            if parameter.mode == "blocked" and key not in seen:
                seen.add(key)
                items.append(
                    ManualFillItem(
                        key=key, kind="drawing_param", label=parameter.label,
                        reason=str(
                            parameter.blocked_reason
                            or "Engine did not derive this dimension; supply directly."
                        ),
                        unit=parameter.unit or "in",
                    )
                )

    return ManualFillPlan(items=items)
